#ce fichier contient la config partagée avec toute l'application


#    si eureka tourne sur un serveur ailleurs on ajoute la config suivante en renseignant l'url du serveur
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
