server:
  port: 8085

spring:
  datasource:
    username: 'root'
    url: jdbc:mysql://localhost:3306/karima_springcloud_tp?serverTimezone=UTC
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true


