server:
  port: 8090
spring:
  datasource:
    username: 'root'
    url: jdbc:mysql://localhost:3306/karima_springcloud_tp?serverTimezone=UTC
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
#    si eureka tourne sur un serveur ailleurs on ajoute la config suivante en renseignant l'url du serveur
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
